#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Usage: $0 NUMBER_OF_USERS"
    echo "This script will create terminal pods starting from user1, up"
    echo "to the specified number. The password for each user is openshift."
	exit 1
fi

MAX=$1
PROJ=terminals

oc get project $PROJ &> /dev/null
if [ "$?" -eq "0" ]; then
  oc project $PROJ >> /dev/null
else
  oc new-project $PROJ >> /dev/null
fi

set -e

oc new-build \
  docker.io/centos/go-toolset-7-centos7~https://github.com/kwkoo/gotty.git \
  --name gotty-builder

sleep 3

oc new-build \
  --name gotty \
  --source-image=gotty-builder \
  --source-image-path=/opt/app-root/bin.tar:. \
  --dockerfile=$'FROM centos:7\nCOPY bin.tar /usr/local/bin/bin.tar\nRUN cd /usr/local/bin && tar -xf bin.tar && rm bin.tar && yum update -y && yum install -y git curl vim nano tmux && yum clean all -y && cd /tmp && curl -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v3/clients/3.11.123/linux/oc.tar.gz && tar -zxf oc.tar.gz && mv oc /usr/local/bin/ && rm -f oc.tar.gz && useradd -m -u 1001 -g 0 user && chown -R 0 /etc/passwd /home/user && chmod -R g=u /etc/passwd /home/user && echo "openshift" | passwd user --stdin\nUSER 1001\nWORKDIR /home/user\nCMD ["/usr/local/bin/startgotty"]\nEXPOSE 8080' \
  --allow-missing-imagestream-tags \
  --strategy=docker

sleep 3

INDEX=0
while [ "$INDEX" -lt "$MAX" ]; do
    INDEX=$((INDEX+1))
    USERNAME="user${INDEX}"
    echo "Creating ${USERNAME}..."
    oc new-app \
      gotty \
      --allow-missing-imagestream-tags \
      -e USER=user \
      -e HOME=/home/user \
      -e OPTIONS="-c $USERNAME:openshift" \
      --name=${USERNAME}
    oc expose dc/${USERNAME} --port 8080
    oc expose svc/${USERNAME}
    oc patch route/${USERNAME} --patch='{"spec":{"tls":{"termination":"edge"}}}'
done